# Table of Contents
## 1. Load csv files into dataframes
## 2. Drops rows from 'secs' dataframe
## 3. Merges dataframes and assigns merged dataframe to 'barsCombined' and saves to 'newBarsCombined.csv'
## 4. Renames columns in 'barCombined'
## 5. Parses 'date' column and creates 'day', 'month', 'year', and 'confirm_time' columns.
## 6. Ensures column titles are lowercase
## 7. Fills NAs
## 8. Ensure time is a string
## 9. Creates 'day_of_week' column (Mon-Fri)
## 10. Drops specific dates from 'barsCombined'
## 11. Creates 'market_open_09:30' column to show opening price of market for each days rows
## 12. Creates 'initial_direction' row which indicates the movement of the market for that row/time in relation to 'market_open_09:30' and saves it to 'newBarsCombined.csv'
## 13. Merges dataframes created 'cleaning' dataframe that now has 'contract_location' column and saves to 'cleaning.csv'

## 1.

In [1]:
import pandas as pd

# Load the CSV files/Datasets
barsCombined = pd.read_csv("GoodOldGoodOld.csv")
secs = pd.read_csv("NewGoodOldGoodOld.csv")

# Inspect the first few rows
print(barsCombined.info())
print(secs.info())

<class 'pandas.DataFrame'>
RangeIndex: 27342 entries, 0 to 27341
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      27342 non-null  str
 1   open      27342 non-null  float64
 2   high      27342 non-null  float64
 3   low       27342 non-null  float64
 4   close     27342 non-null  float64
 5   volume    27342 non-null  float64
 6   average   27342 non-null  float64
 7   barCount  27342 non-null  int64
 8   time      27342 non-null  str
dtypes: float64(6), int64(1), str(2)
memory usage: 1.9 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 9937 entries, 0 to 9936
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    9937 non-null   str
 1   open    9937 non-null   float64
 2   high    9937 non-null   float64
 3   low     9937 non-null   float64
 4   close   9937 non-null   float64
 5   volume  9937 non-null   int64
 6   time    9937 non-null   str
dtypes: float64(4), int64(1), str(2)
memory usage: 543.6 KB
None

## 2.
## These rows had no volume

In [2]:
# Drop rows with zero volume (pre-market data before an identified gap)
print(secs.head())

# NOTE: The number 1140 represents the exact count of zero-volume rows
# from the IBKR 1-sec feed before a known data gap in NewGoodOldGoodOld.csv.
# If new sec data is ever prepended to that file, this number must be
# recalculated. A more robust alternative that auto-detects zero-volume rows:
#   secs = secs[secs['volume'] > 0].reset_index(drop=True)
secs = secs.iloc[1140:].reset_index(drop=True)

print(secs.head())

                        date      open      high       low     close  volume  \
0  2024-03-11 09:30:01-04:00  5176.750  5176.750  5176.750  5176.750       0
1  2024-03-11 09:30:02-04:00  5176.750  5176.750  5176.750  5176.750       0
2  2024-03-11 09:30:03-04:00  5176.875  5176.875  5176.875  5176.875       0
3  2024-03-11 09:30:05-04:00  5178.000  5178.000  5178.000  5178.000       0
4  2024-03-11 09:30:08-04:00  5178.875  5178.875  5178.875  5178.875       0

       time
0  09:30:01
1  09:30:02
2  09:30:03
3  09:30:05
4  09:30:08
                        date      open      high       low     close  volume  \
0  2024-06-05 09:30:01-04:00  5327.875  5327.875  5327.875  5327.875       0
1  2024-06-05 09:30:02-04:00  5327.375  5327.375  5327.375  5327.375       0
2  2024-06-05 09:30:03-04:00  5326.375  5326.375  5326.375  5326.375       0
3  2024-06-05 09:30:05-04:00  5326.125  5326.125  5326.125  5326.125       0
4  2024-06-05 09:30:08-04:00  5326.125  5326.125  5326.125  5326.125       0

       time
0  09:30:01
1  09:30:02
2  09:30:03
3  09:30:05
4  09:30:08

## 3.

In [3]:
# Merge the datasets on ['date', 'candle_open_price', 'candle_high_price', 'candle_low_price', 
#'candle_close_price', 'volume', 'average', 'bar_count', 'time',
#'confirm_time', 'year', 'month', 'day', 'day_of_week']

barsCombined = pd.merge(
    barsCombined,
    secs,
    on=['date', 'open', 'high', 'low', 'close', 'volume', 'time'],  # Align on these keys
    how="outer"  # Include all rows from both datasets
)

# Sort the final dataset by 'id' in ascending order
barsCombined = barsCombined.sort_values(by=["date", 'time'], ascending=True).reset_index(drop=True)

# Save the final sorted dataset to a CSV file
barsCombined.to_csv("newBarsCombined.csv", index=False)
print("barsCombined dataset sorted and saved as 'newBarsCombined.csv'")

barsCombined dataset sorted and saved as 'newBarsCombined.csv'

## 4.

In [4]:
barsCombined= barsCombined.rename(columns = {'open':'candle_open_price', 'high': 'candle_high_price', 'low':'candle_low_price',
                                     'close':'candle_close_price', 'average_price':'candle_average_price', 'barCount':'bar_count'})
barsCombined.info()

<class 'pandas.DataFrame'>
RangeIndex: 36139 entries, 0 to 36138
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                36139 non-null  str
 1   candle_open_price   36139 non-null  float64
 2   candle_high_price   36139 non-null  float64
 3   candle_low_price    36139 non-null  float64
 4   candle_close_price  36139 non-null  float64
 5   volume              36139 non-null  float64
 6   average             27342 non-null  float64
 7   bar_count           27342 non-null  float64
 8   time                36139 non-null  str
dtypes: float64(7), str(2)
memory usage: 2.5 MB

## 5.

In [5]:
import pandas as pd
from datetime import datetime

# Check the first few values
print(barsCombined["date"].head())

# Step 1: Remove the timezone information while keeping the local time
try:
    barsCombined["date"] = barsCombined["date"].apply(lambda x: datetime.strptime(x[:-6], "%Y-%m-%d %H:%M:%S") if isinstance(x, str) else x)
    print("✅ Date column successfully parsed without timezone shift!\n")
except Exception as e:
    print(f"❌ Error while parsing date column: {e}")

# Step 2: Ensure 'date' is converted properly
if not pd.api.types.is_datetime64_any_dtype(barsCombined["date"]):
    print("⚠ Warning: 'date' column is not in datetime format. Check your data!")
else:
    print("✅ 'date' column is confirmed as datetime!\n")

# Step 3: Extract time and separate components
if "date" in barsCombined.columns and pd.api.types.is_datetime64_any_dtype(barsCombined["date"]):
    barsCombined["confirm_time"] = barsCombined["date"].dt.strftime("%H:%M:%S")  # Extract local time
    barsCombined["date"] = barsCombined["date"].dt.date  # Keep only the date (YYYY-MM-DD)
    print("✅ Successfully extracted 'confirm_time' and cleaned 'date'.\n")
else:
    print("⚠ Skipping extraction because 'date' is not in datetime format.")

# Step 4: Extract Year, Month, and Day into separate columns
if "date" in barsCombined.columns:
    barsCombined["year"] = pd.to_datetime(barsCombined["date"], errors="coerce").dt.year
    barsCombined["month"] = pd.to_datetime(barsCombined["date"], errors="coerce").dt.month
    barsCombined["day"] = pd.to_datetime(barsCombined["date"], errors="coerce").dt.day
    print("✅ 'year', 'month', and 'day' columns created successfully!\n")
else:
    print("⚠ Skipping year, month, and day extraction as 'date' column does not exist.")

# Step 5: Display the updated dataset
print(barsCombined[["date", "confirm_time", "year", "month", "day"]].head())

0    2024-03-11 07:00:00-04:00
1    2024-03-11 07:15:00-04:00
2    2024-03-11 07:30:00-04:00
3    2024-03-11 07:45:00-04:00
4    2024-03-11 08:00:00-04:00
Name: date, dtype: str
✅ Date column successfully parsed without timezone shift!

✅ 'date' column is confirmed as datetime!

✅ Successfully extracted 'confirm_time' and cleaned 'date'.

✅ 'year', 'month', and 'day' columns created successfully!

         date confirm_time  year  month  day
0  2024-03-11     07:00:00  2024      3   11
1  2024-03-11     07:15:00  2024      3   11
2  2024-03-11     07:30:00  2024      3   11
3  2024-03-11     07:45:00  2024      3   11
4  2024-03-11     08:00:00  2024      3   11

## 6.

In [6]:
# Import necessary libraries
import pandas as pd
from datetime import datetime

# Ensure all column names are lowercase for consistency
barsCombined.columns = barsCombined.columns.str.lower()

print(barsCombined.info())

<class 'pandas.DataFrame'>
RangeIndex: 36139 entries, 0 to 36138
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                36139 non-null  object
 1   candle_open_price   36139 non-null  float64
 2   candle_high_price   36139 non-null  float64
 3   candle_low_price    36139 non-null  float64
 4   candle_close_price  36139 non-null  float64
 5   volume              36139 non-null  float64
 6   average             27342 non-null  float64
 7   bar_count           27342 non-null  float64
 8   time                36139 non-null  str
 9   confirm_time        36139 non-null  str
 10  year                36139 non-null  int32
 11  month               36139 non-null  int32
 12  day                 36139 non-null  int32
dtypes: float64(7), int32(3), object(1), str(2)
memory usage: 3.2+ MB
None

## 7.

In [7]:
if barsCombined[['year', 'month', 'day']].isna().any().any():
    barsCombined["year"] = barsCombined["year"].fillna(0).astype(int)
    barsCombined["month"] = barsCombined["month"].fillna(0).astype(int)
    barsCombined["day"] = barsCombined["day"].fillna(0).astype(int)
    print("NA values existed in nadex and were filled.")
else:
    print("No NA values were found in barsCombined 'year', 'month', 'day' columns!")

print(barsCombined.head())

No NA values were found in barsCombined 'year', 'month', 'day' columns!
         date  candle_open_price  candle_high_price  candle_low_price  \
0  2024-03-11            5188.00            5188.25           5185.75
1  2024-03-11            5186.50            5187.50           5186.00
2  2024-03-11            5184.50            5184.75           5183.00
3  2024-03-11            5182.75            5183.25           5182.25
4  2024-03-11            5179.50            5179.50           5176.50

   candle_close_price  volume  average  bar_count      time confirm_time  \
0             5186.00    -1.0     -1.0       -1.0  07:00:00     07:00:00
1             5186.25    -1.0     -1.0       -1.0  07:15:00     07:15:00
2             5183.50    -1.0     -1.0       -1.0  07:30:00     07:30:00
3             5182.75    -1.0     -1.0       -1.0  07:45:00     07:45:00
4             5177.50    -1.0     -1.0       -1.0  08:00:00     08:00:00

   year  month  day
0  2024      3   11
1  2024      3   11
2  2024      3   11
3  2024      3   11
4  2024      3   11

## 8.

In [8]:
# Ensure 'time' is a string in nadex

barsCombined["time"] = barsCombined["time"].astype(str)

barsCombined["year"] = barsCombined["year"].astype(int)
barsCombined["month"] = barsCombined["month"].astype(int)
barsCombined["day"] = barsCombined["day"].astype(int)

print(barsCombined.info())

<class 'pandas.DataFrame'>
RangeIndex: 36139 entries, 0 to 36138
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                36139 non-null  object
 1   candle_open_price   36139 non-null  float64
 2   candle_high_price   36139 non-null  float64
 3   candle_low_price    36139 non-null  float64
 4   candle_close_price  36139 non-null  float64
 5   volume              36139 non-null  float64
 6   average             27342 non-null  float64
 7   bar_count           27342 non-null  float64
 8   time                36139 non-null  str
 9   confirm_time        36139 non-null  str
 10  year                36139 non-null  int64
 11  month               36139 non-null  int64
 12  day                 36139 non-null  int64
dtypes: float64(7), int64(3), object(1), str(2)
memory usage: 3.6+ MB
None

In [9]:
barsCombined.head()

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,year,month,day
0,2024-03-11,5188.00,5188.25,5185.75,5186.00,-1.0,-1.0,-1.0,07:00:00,07:00:00,2024,3,11
1,2024-03-11,5186.50,5187.50,5186.00,5186.25,-1.0,-1.0,-1.0,07:15:00,07:15:00,2024,3,11
2,2024-03-11,5184.50,5184.75,5183.00,5183.50,-1.0,-1.0,-1.0,07:30:00,07:30:00,2024,3,11
3,2024-03-11,5182.75,5183.25,5182.25,5182.75,-1.0,-1.0,-1.0,07:45:00,07:45:00,2024,3,11
4,2024-03-11,5179.50,5179.50,5176.50,5177.50,-1.0,-1.0,-1.0,08:00:00,08:00:00,2024,3,11

## 9.

In [10]:
import pandas as pd

# Vectorized day-of-week using pandas datetime accessor
# Replaces a slow row-by-row .apply() lambda
barsCombined["day_of_week"] = pd.to_datetime(barsCombined["date"]).dt.day_name()

barsCombined.head(15850)

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,year,month,day,day_of_week
0,2024-03-11,5188.000,5188.250,5185.750,5186.000,-1.0,-1.0,-1.0,07:00:00,07:00:00,2024,3,11,Monday
1,2024-03-11,5186.500,5187.500,5186.000,5186.250,-1.0,-1.0,-1.0,07:15:00,07:15:00,2024,3,11,Monday
2,2024-03-11,5184.500,5184.750,5183.000,5183.500,-1.0,-1.0,-1.0,07:30:00,07:30:00,2024,3,11,Monday
3,2024-03-11,5182.750,5183.250,5182.250,5182.750,-1.0,-1.0,-1.0,07:45:00,07:45:00,2024,3,11,Monday
4,2024-03-11,5179.500,5179.500,5176.500,5177.500,-1.0,-1.0,-1.0,08:00:00,08:00:00,2024,3,11,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15845,2025-02-24,6049.625,6049.625,6049.625,6049.625,0.0,NaN,NaN,09:30:35,09:30:35,2025,2,24,Monday
15846,2025-02-24,6048.875,6048.875,6048.875,6048.875,0.0,NaN,NaN,09:30:40,09:30:40,2025,2,24,Monday
15847,2025-02-24,6050.125,6050.125,6050.125,6050.125,0.0,NaN,NaN,09:30:45,09:30:45,2025,2,24,Monday
15848,2025-02-24,6050.875,6050.875,6050.875,6050.875,0.0,NaN,NaN,09:30:50,09:30:50,2025,2,24,Monday
15849,2025-02-24,6049.875,6049.875,6049.875,6049.875,0.0,NaN,NaN,09:30:55,09:30:55,2025,2,24,Monday

## 10.

In [11]:
import pandas as pd

barsCombined['date'] = pd.to_datetime(barsCombined['date']).dt.date

# CME early-close and holiday dates excluded from analysis
# (shortened sessions produce abnormal close prices that skew strategy results)
# Add new dates as needed — check: https://www.cmegroup.com/tools-information/holiday-calendar.html
EXCLUDED_DATES = [
    pd.to_datetime('2024-11-29').date(),  # Black Friday (early close)
    pd.to_datetime('2024-12-24').date(),  # Christmas Eve (early close)
    pd.to_datetime('2024-07-03').date(),  # Day before Independence Day (early close)
    pd.to_datetime('2023-07-03').date(),  # Day before Independence Day (early close)
    pd.to_datetime('2023-11-24').date(),  # Black Friday (early close)
]

barsCombined = barsCombined[~barsCombined['date'].isin(EXCLUDED_DATES)]

# Reset index so there are no gaps after filtering
barsCombined = barsCombined.reset_index(drop=True)

barsCombined.head(15850)

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,year,month,day,day_of_week
0,2024-03-11,5188.00,5188.25,5185.75,5186.00,-1.0,-1.0,-1.0,07:00:00,07:00:00,2024,3,11,Monday
1,2024-03-11,5186.50,5187.50,5186.00,5186.25,-1.0,-1.0,-1.0,07:15:00,07:15:00,2024,3,11,Monday
2,2024-03-11,5184.50,5184.75,5183.00,5183.50,-1.0,-1.0,-1.0,07:30:00,07:30:00,2024,3,11,Monday
3,2024-03-11,5182.75,5183.25,5182.25,5182.75,-1.0,-1.0,-1.0,07:45:00,07:45:00,2024,3,11,Monday
4,2024-03-11,5179.50,5179.50,5176.50,5177.50,-1.0,-1.0,-1.0,08:00:00,08:00:00,2024,3,11,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15845,2025-02-26,6014.00,6014.25,6010.00,6013.25,-1.0,-1.0,-1.0,10:15:00,10:15:00,2025,2,26,Wednesday
15846,2025-02-26,6014.50,6016.50,6011.00,6013.00,-1.0,-1.0,-1.0,10:25:00,10:25:00,2025,2,26,Wednesday
15847,2025-02-26,6007.25,6012.75,6007.00,6012.50,-1.0,-1.0,-1.0,10:30:00,10:30:00,2025,2,26,Wednesday
15848,2025-02-26,6010.50,6016.00,6009.25,6015.75,-1.0,-1.0,-1.0,10:40:00,10:40:00,2025,2,26,Wednesday
15849,2025-02-26,6015.50,6016.00,6012.50,6014.00,-1.0,-1.0,-1.0,10:45:00,10:45:00,2025,2,26,Wednesday

## 11.

In [12]:
import pandas as pd

# Convert 'date' column to a datetime object
barsCombined["date"] = pd.to_datetime(barsCombined["date"])

barsCombined["date"] = barsCombined["date"].dt.strftime("%Y-%m-%d")

# Assign `candle_open_price` where time is `09:30:00`
barsCombined.loc[barsCombined["time"] == "09:30:00", "market_open_09:30"] = barsCombined["candle_open_price"]

# Forward-fill missing values so every row has the last seen 09:30:00 price
barsCombined["market_open_09:30"] = barsCombined["market_open_09:30"].ffill()

barsCombined.info()

<class 'pandas.DataFrame'>
RangeIndex: 35974 entries, 0 to 35973
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                35974 non-null  str
 1   candle_open_price   35974 non-null  float64
 2   candle_high_price   35974 non-null  float64
 3   candle_low_price    35974 non-null  float64
 4   candle_close_price  35974 non-null  float64
 5   volume              35974 non-null  float64
 6   average             27234 non-null  float64
 7   bar_count           27234 non-null  float64
 8   time                35974 non-null  str
 9   confirm_time        35974 non-null  str
 10  year                35974 non-null  int64
 11  month               35974 non-null  int64
 12  day                 35974 non-null  int64
 13  day_of_week         35974 non-null  str
 14  market_open_09:30   35964 non-null  float64
dtypes: float64(8), int64(3), str(4)
memory usage: 4.1 MB

In [13]:
barsCombined.head()

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,year,month,day,day_of_week,market_open_09:30
0,2024-03-11,5188.00,5188.25,5185.75,5186.00,-1.0,-1.0,-1.0,07:00:00,07:00:00,2024,3,11,Monday,NaN
1,2024-03-11,5186.50,5187.50,5186.00,5186.25,-1.0,-1.0,-1.0,07:15:00,07:15:00,2024,3,11,Monday,NaN
2,2024-03-11,5184.50,5184.75,5183.00,5183.50,-1.0,-1.0,-1.0,07:30:00,07:30:00,2024,3,11,Monday,NaN
3,2024-03-11,5182.75,5183.25,5182.25,5182.75,-1.0,-1.0,-1.0,07:45:00,07:45:00,2024,3,11,Monday,NaN
4,2024-03-11,5179.50,5179.50,5176.50,5177.50,-1.0,-1.0,-1.0,08:00:00,08:00:00,2024,3,11,Monday,NaN

## 12.

In [14]:
import pandas as pd
import numpy as np

# Vectorized initial direction — replaces a slow row-by-row .apply() function.
# 'above': bar opened higher than the market open -> expect reversal DOWN
# 'below': bar opened lower than the market open  -> expect reversal UP
# 'equal': bar opened exactly at market open (filtered out in next notebook)
barsCombined['initial_direction'] = np.where(
    barsCombined['candle_open_price'] > barsCombined['market_open_09:30'], 'above',
    np.where(barsCombined['candle_open_price'] < barsCombined['market_open_09:30'], 'below', 'equal')
)

barsCombined.to_csv('newBarsCombined.csv', index=False)

## 13.
## xlsx file is imported and contains contract locations above and below market open. Script then assigns either 'above' value or 'below' value to each row dependent on 'initial_direction'

In [15]:
import pandas as pd
import numpy as np

# Load contract locations (produced by getNadexContracts.ipynb)
df_contracts = pd.read_csv("contract_locations.csv", parse_dates=["date"])
df_contracts["date"] = df_contracts["date"].dt.normalize()

barsCombined["date"] = pd.to_datetime(barsCombined["date"]).dt.normalize()

# Warn about dates not yet covered by contract_locations.csv
missing = barsCombined[~barsCombined["date"].isin(df_contracts["date"])]["date"].dt.date.unique()
if len(missing):
    print(f"WARNING: {len(missing)} date(s) missing from contract_locations.csv")
    print(f"  Run getNadexContracts.ipynb first to cover these dates.")
    print(f"  First 5 missing: {missing[:5]}")
else:
    print(f"contract_locations.csv covers all {len(df_contracts)} date(s) in dataset")

# Merge contract strikes into main dataframe
cleaning = barsCombined.merge(df_contracts, on="date", how="left")

# Vectorized contract_location assignment (replaces slow .iterrows() loop)
# Strategy logic:
#   initial_direction == "below" -> expect UP reversal -> contract is the ABOVE strike
#   initial_direction == "above" -> expect DOWN reversal -> contract is the BELOW strike
#   initial_direction == "equal" -> no position (NaN)
conditions = [
    cleaning["initial_direction"] == "below",
    cleaning["initial_direction"] == "above",
]
choices = [cleaning["above"], cleaning["below"]]
cleaning["contract_location"] = np.select(conditions, choices, default=np.nan)

print(cleaning.head(300))
cleaning.to_csv("cleaning.csv", index=False)

WARNING: 26 date(s) missing from contract_locations.csv
  Run getNadexContracts.ipynb first to cover these dates.
  First 5 missing: [datetime.date(2024, 5, 27) datetime.date(2024, 6, 17)
 datetime.date(2024, 6, 18) datetime.date(2024, 6, 19)
 datetime.date(2024, 7, 4)]
          date  candle_open_price  candle_high_price  candle_low_price  \
0   2024-03-11            5188.00            5188.25           5185.75
1   2024-03-11            5186.50            5187.50           5186.00
2   2024-03-11            5184.50            5184.75           5183.00
3   2024-03-11            5182.75            5183.25           5182.25
4   2024-03-11            5179.50            5179.50           5176.50
..         ...                ...                ...               ...
295 2024-03-15            5178.00            5179.25           5177.00
296 2024-03-15            5179.50            5179.50           5177.25
297 2024-03-15            5177.25            5180.25           5176.75
298 2024-03-15            5184.00            5185.25           5183.25
299 2024-03-15            5179.00            5180.25           5178.50

     candle_close_price  volume  average  bar_count      time confirm_time  \
0               5186.00    -1.0     -1.0       -1.0  07:00:00     07:00:00
1               5186.25    -1.0     -1.0       -1.0  07:15:00     07:15:00
2               5183.50    -1.0     -1.0       -1.0  07:30:00     07:30:00
3               5182.75    -1.0     -1.0       -1.0  07:45:00     07:45:00
4               5177.50    -1.0     -1.0       -1.0  08:00:00     08:00:00
..                  ...     ...      ...        ...       ...          ...
295             5178.00    -1.0     -1.0       -1.0  13:30:00     13:30:00
296             5177.75    -1.0     -1.0       -1.0  13:45:00     13:45:00
297             5180.00    -1.0     -1.0       -1.0  13:53:00     13:53:00
298             5185.00    -1.0     -1.0       -1.0  14:00:00     14:00:00
299             5179.25    -1.0     -1.0       -1.0  14:15:00     14:15:00

     year  month  day day_of_week  market_open_09:30 initial_direction  \
0    2024      3   11      Monday                NaN             equal
1    2024      3   11      Monday                NaN             equal
2    2024      3   11      Monday                NaN             equal
3    2024      3   11      Monday                NaN             equal
4    2024      3   11      Monday                NaN             equal
..    ...    ...  ...         ...                ...               ...
295  2024      3   15      Friday            5186.25             below
296  2024      3   15      Friday            5186.25             below
297  2024      3   15      Friday            5186.25             below
298  2024      3   15      Friday            5186.25             below
299  2024      3   15      Friday            5186.25             below

      above   below  market_open  contract_location
0    5181.0  5169.0      5177.75                NaN
1    5181.0  5169.0      5177.75                NaN
2    5181.0  5169.0      5177.75                NaN
3    5181.0  5169.0      5177.75                NaN
4    5181.0  5169.0      5177.75                NaN
..      ...     ...          ...                ...
295  5194.0  5182.0      5186.25             5194.0
296  5194.0  5182.0      5186.25             5194.0
297  5194.0  5182.0      5186.25             5194.0
298  5194.0  5182.0      5186.25             5194.0
299  5194.0  5182.0      5186.25             5194.0

[300 rows x 20 columns]