# Table of Contents
## 1. Imports 'cleaning.csv' into 'cleaning' dataframe and creates 'market_close_16:15' column showing where the market price closed for each day
## 2. Does the same at 1. but creates 'market_reg_close_16:00'
## 3. Removes from 'cleaning' df 'initial_direction'== 'equal' rows and assign those rows to 'equal_rows'. Saves dataframes to csv files
## 4. Creates dataframe of just rows where 'time'== '09:30:00' and saves to csv file

## 1.

In [160]:
import pandas as pd

cleaning= pd.read_csv('cleaning.csv')

# 1. Ensure 'date' is in a standardized date format (if it's still a string).
#    If it's already datetime or if you only need the date string, you can skip this step.
cleaning['date'] = pd.to_datetime(cleaning['date'])

# 2. Create a mapping from date -> candle_open_price for rows where confirm_time == '16:15:00'.
#    Drop duplicates in case multiple rows for the same date have confirm_time == '16:15:00'.
mapping = (
    cleaning.loc[cleaning['confirm_time'] == '16:15:00', ['date', 'candle_open_price']]
      .drop_duplicates('date')
      .set_index('date')['candle_open_price']
)

# 3. Create the new column 'market_close_16:15' by mapping each row's date to the above Series.
#    This will fill the column with NaN if there's no matching date in the mapping.
cleaning['market_close_16:15'] = cleaning['date'].map(mapping)

# Now df has a new column 'market_close_16:15' that, for each date,
# holds the candle_open_price from the row where confirm_time == '16:15:00' for that date.
print(cleaning.head(75))  # Check the first 20 rows to verify

         date  candle_open_price  candle_high_price  candle_low_price  \
0  2022-12-12            3976.25            3981.50           3974.75
1  2022-12-12            3980.00            3980.50           3976.00
2  2022-12-12            3977.25            3979.25           3975.25
3  2022-12-12            3978.50            3979.75           3975.50
4  2022-12-12            3978.50            3979.00           3973.75
..        ...                ...                ...               ...
70 2022-12-13            4115.75            4117.25           4113.50
71 2022-12-13            4114.25            4116.25           4108.50
72 2022-12-13            4095.25            4095.50           4085.75
73 2022-12-13            4092.00            4093.00           4084.75
74 2022-12-13            4073.25            4080.25           4073.25

    candle_close_price   volume   average  bar_count      time confirm_time  \
0              3980.00  13850.0  3977.425       4176  09:30:00     09:30:00
1              3977.50   8373.0  3977.900       2593  09:31:00     09:31:00
2              3978.50   5649.0  3977.150       1895  09:32:00     09:32:00
3              3978.75   5903.0  3978.200       2027  09:33:00     09:33:00
4              3974.50   5902.0  3975.675       1996  09:34:00     09:34:00
..                 ...      ...       ...        ...       ...          ...
70             4116.75   4224.0  4115.475       1459  10:13:00     10:13:00
71             4114.75   7390.0  4112.650       2750  10:15:00     10:15:00
72             4090.50  10528.0  4089.225       3450  10:25:00     10:25:00
73             4087.50   7235.0  4088.075       2353  10:30:00     10:30:00
74             4079.50   8527.0  4077.100       3172  10:40:00     10:40:00

    year  month  day day_of_week  market_open_09:30 initial_direction_open  \
0   2022     12   12      Monday            3976.25                  equal
1   2022     12   12      Monday            3976.25                  above
2   2022     12   12      Monday            3976.25                  above
3   2022     12   12      Monday            3976.25                  above
4   2022     12   12      Monday            3976.25                  above
..   ...    ...  ...         ...                ...                    ...
70  2022     12   13     Tuesday            4140.00                  below
71  2022     12   13     Tuesday            4140.00                  below
72  2022     12   13     Tuesday            4140.00                  below
73  2022     12   13     Tuesday            4140.00                  below
74  2022     12   13     Tuesday            4140.00                  below

     above   below  contract_location  market_close_16:15
0   3980.0  3968.0                NaN             4020.25
1   3980.0  3968.0             3968.0             4020.25
2   3980.0  3968.0             3968.0             4020.25
3   3980.0  3968.0             3968.0             4020.25
4   3980.0  3968.0             3968.0             4020.25
..     ...     ...                ...                 ...
70  4152.0  4140.0             4152.0             4055.50
71  4152.0  4140.0             4152.0             4055.50
72  4152.0  4140.0             4152.0             4055.50
73  4152.0  4140.0             4152.0             4055.50
74  4152.0  4140.0             4152.0             4055.50

[75 rows x 20 columns]

In [162]:
cleaning.head()

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,year,month,day,day_of_week,market_open_09:30,initial_direction_open,above,below,contract_location,market_close_16:15
0,2022-12-12,3976.25,3981.50,3974.75,3980.00,13850.0,3977.425,4176,09:30:00,09:30:00,2022,12,12,Monday,3976.25,equal,3980.0,3968.0,NaN,4020.25
1,2022-12-12,3980.00,3980.50,3976.00,3977.50,8373.0,3977.900,2593,09:31:00,09:31:00,2022,12,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25
2,2022-12-12,3977.25,3979.25,3975.25,3978.50,5649.0,3977.150,1895,09:32:00,09:32:00,2022,12,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25
3,2022-12-12,3978.50,3979.75,3975.50,3978.75,5903.0,3978.200,2027,09:33:00,09:33:00,2022,12,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25
4,2022-12-12,3978.50,3979.00,3973.75,3974.50,5902.0,3975.675,1996,09:34:00,09:34:00,2022,12,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25

## 2.

In [ ]:
import pandas as pd

# 1. Ensure 'date' is in a standardized date format (if it's still a string).
#    If it's already datetime or if you only need the date string, you can skip this step.
cleaning['date'] = pd.to_datetime(cleaning['date'])

# 2. Create a mapping from date -> candle_open_price for rows where confirm_time == '16:00:00'.
#    Drop duplicates in case multiple rows for the same date have confirm_time == '16:00:00'.
mapping = (
    cleaning.loc[cleaning['confirm_time'] == '16:00:00', ['date', 'candle_open_price']]
      .drop_duplicates('date')
      .set_index('date')['candle_open_price']
)

# 3. Create the new column 'market_close_16:00' by mapping each row's date to the above Series.
#    This will fill the column with NaN if there's no matching date in the mapping.
cleaning['market_reg_close_16:00'] = cleaning['date'].map(mapping)

# Now df has a new column 'market_close_16:00' that, for each date,
# holds the candle_open_price from the row where confirm_time == '16:00:00' for that date.
print(cleaning.head(75))  # Check the first 20 rows to verify

cleaning.to_csv('cleaning.csv', index= False)

In [166]:
cleaning.head()

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,...,month,day,day_of_week,market_open_09:30,initial_direction_open,above,below,contract_location,market_close_16:15,market_close_16:00
0,2022-12-12,3976.25,3981.50,3974.75,3980.00,13850.0,3977.425,4176,09:30:00,09:30:00,...,12,12,Monday,3976.25,equal,3980.0,3968.0,NaN,4020.25,4025.75
1,2022-12-12,3980.00,3980.50,3976.00,3977.50,8373.0,3977.900,2593,09:31:00,09:31:00,...,12,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75
2,2022-12-12,3977.25,3979.25,3975.25,3978.50,5649.0,3977.150,1895,09:32:00,09:32:00,...,12,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75
3,2022-12-12,3978.50,3979.75,3975.50,3978.75,5903.0,3978.200,2027,09:33:00,09:33:00,...,12,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75
4,2022-12-12,3978.50,3979.00,3973.75,3974.50,5902.0,3975.675,1996,09:34:00,09:34:00,...,12,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75

## 3.

In [169]:
# Filter rows where 'initial_direction_open' is 'equal'
equal_rows = cleaning[cleaning['initial_direction_open'] == 'equal']

# Save these rows separately for future analysis
equal_rows.to_csv('equal_rows.csv', index=False)

print(equal_rows.head())

# Remove these rows from the main dataset
clean = cleaning[cleaning['initial_direction_open'] != 'equal']

clean.to_csv('clean.csv', index=False) 

print(clean.head())

          date  candle_open_price  candle_high_price  candle_low_price  \
0   2022-12-12            3976.25            3981.50           3974.75
52  2022-12-13            4140.00            4141.00           4135.00
104 2022-12-14            4051.75            4058.00           4051.25
156 2022-12-15            3976.00            3984.00           3974.75
208 2022-12-16            3898.50            3901.25           3895.00

     candle_close_price   volume   average  bar_count      time confirm_time  \
0               3980.00  13850.0  3977.425       4176  09:30:00     09:30:00
52              4135.50  17486.0  4136.950       5918  09:30:00     09:30:00
104             4056.50  11674.0  4055.125       3536  09:30:00     09:30:00
156             3981.25  15076.0  3979.900       4892  09:30:00     09:30:00
208             3898.50  21198.0  3897.925       5579  09:30:00     09:30:00

     ...  month  day  day_of_week market_open_09:30  initial_direction_open  \
0    ...     12   12       Monday           3976.25                   equal
52   ...     12   13      Tuesday           4140.00                   equal
104  ...     12   14    Wednesday           4051.75                   equal
156  ...     12   15     Thursday           3976.00                   equal
208  ...     12   16       Friday           3898.50                   equal

      above   below  contract_location  market_close_16:15  market_close_16:00
0    3980.0  3968.0                NaN             4020.25             4025.75
52   4152.0  4140.0                NaN             4055.50             4056.00
104  4054.0  4042.0                NaN             4038.25             4029.25
156  3979.0  3967.0                NaN             3922.25             3927.00
208  3910.0  3898.0                NaN             3872.75             3877.75

[5 rows x 21 columns]
        date  candle_open_price  candle_high_price  candle_low_price  \
1 2022-12-12            3980.00            3980.50           3976.00
2 2022-12-12            3977.25            3979.25           3975.25
3 2022-12-12            3978.50            3979.75           3975.50
4 2022-12-12            3978.50            3979.00           3973.75
5 2022-12-12            3974.75            3978.25           3974.25

   candle_close_price  volume   average  bar_count      time confirm_time  \
1             3977.50  8373.0  3977.900       2593  09:31:00     09:31:00
2             3978.50  5649.0  3977.150       1895  09:32:00     09:32:00
3             3978.75  5903.0  3978.200       2027  09:33:00     09:33:00
4             3974.50  5902.0  3975.675       1996  09:34:00     09:34:00
5             3976.50  6085.0  3976.350       2002  09:35:00     09:35:00

   ...  month  day  day_of_week market_open_09:30  initial_direction_open  \
1  ...     12   12       Monday           3976.25                   above
2  ...     12   12       Monday           3976.25                   above
3  ...     12   12       Monday           3976.25                   above
4  ...     12   12       Monday           3976.25                   above
5  ...     12   12       Monday           3976.25                   below

    above   below  contract_location  market_close_16:15  market_close_16:00
1  3980.0  3968.0             3968.0             4020.25             4025.75
2  3980.0  3968.0             3968.0             4020.25             4025.75
3  3980.0  3968.0             3968.0             4020.25             4025.75
4  3980.0  3968.0             3968.0             4020.25             4025.75
5  3980.0  3968.0             3980.0             4020.25             4025.75

[5 rows x 21 columns]

## 4.

In [146]:
open_rows= equal_rows[equal_rows['time']== '09:30:00']

open_rows= open_rows[['date','market_open_09:30']]

open_rows.to_excel('open_rows.xlsx', index=False)