# Table of Contents
## 1. Load 'clean.csv' dataset in dataframe as 'clean'
## 2. Creates 'day_direction_16:15' column that determines movement of price for the day
## 3. Creates 'day_direction_reg_16:00' column that determines movement of price for the day
## 4. Creates'philo_result' that determines if the startegy was correct or incorrect
## 5. Creates'philo_result' that determines if the startegy was correct or incorrect
## 6. Creates 'diff_open_close' column that shows absolute value difference on the open and closing price of the market
## 7. Creates 'rounded_diff_open_close' column that rounds the 'diff_open_close' value to the nearest integer/whole number
## 8. Creates columns 'open_close_diff_sdv_interval' and 'open_close_diff_nearest_sdv' categorizing the open-close difference
## 9. Creates 'diff_open_conLoc' column that shows absolute value difference on the open of market and 'contract_location' column
## 10. Creates columns 'open_conLoc_diff_sdv_interval' and 'open_conLoc_diff_nearest_sdv' categorizing the open-contract location difference
## 11. Creates columns 'dow_win_streak' and 'dow_loss_streak' that records the win/loss streaks for the 'time' and 'day_of_week' (Mon-Fri)
## 12. Creates columns 'overall_win_streak' and 'overall_loss_streak' that records the win/loss streaks for the 'time'

## 1.

In [18]:
import pandas as pd

clean = pd.read_csv("clean.csv")

In [121]:
clean.head()

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,...,month,day,day_of_week,market_open_09:30,initial_direction_open,above,below,contract_location,market_close_16:15,market_close_16:00
0,2022-12-12,3980.00,3980.50,3976.00,3977.50,8373.0,3977.900,2593,09:31:00,09:31:00,...,12,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75
1,2022-12-12,3977.25,3979.25,3975.25,3978.50,5649.0,3977.150,1895,09:32:00,09:32:00,...,12,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75
2,2022-12-12,3978.50,3979.75,3975.50,3978.75,5903.0,3978.200,2027,09:33:00,09:33:00,...,12,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75
3,2022-12-12,3978.50,3979.00,3973.75,3974.50,5902.0,3975.675,1996,09:34:00,09:34:00,...,12,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75
4,2022-12-12,3974.75,3978.25,3974.25,3976.50,6085.0,3976.350,2002,09:35:00,09:35:00,...,12,12,Monday,3976.25,below,3980.0,3968.0,3980.0,4020.25,4025.75

## 2.

In [20]:
import pandas as pd

# Suppose clean has columns: 'candle_open_price' and 'market_open_09:30'
def determine_direction(row):
    if row['market_open_09:30'] > row['market_close_16:15']:
        return 'down'
    elif row['market_open_09:30'] < row['market_close_16:15']:
        return 'up'
    else:
        return 'equal'

clean['day_direction_16:15']= clean.apply(determine_direction, axis=1)
clean.head()

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,...,day,day_of_week,market_open_09:30,initial_direction,above,below,contract_location,market_close_16:15,market_reg_close_16:00,day_direction_16:15
0,2022-12-12,3980.00,3980.50,3976.00,3977.50,8373.0,3977.900,2593,09:31:00,09:31:00,...,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75,up
1,2022-12-12,3977.25,3979.25,3975.25,3978.50,5649.0,3977.150,1895,09:32:00,09:32:00,...,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75,up
2,2022-12-12,3978.50,3979.75,3975.50,3978.75,5903.0,3978.200,2027,09:33:00,09:33:00,...,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75,up
3,2022-12-12,3978.50,3979.00,3973.75,3974.50,5902.0,3975.675,1996,09:34:00,09:34:00,...,12,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75,up
4,2022-12-12,3974.75,3978.25,3974.25,3976.50,6085.0,3976.350,2002,09:35:00,09:35:00,...,12,Monday,3976.25,below,3980.0,3968.0,3980.0,4020.25,4025.75,up

## 3.

In [23]:
# Suppose clean has columns: 'candle_open_price' and 'market_open_09:30'
def determine_direction(row):
    if row['market_open_09:30'] > row['market_reg_close_16:00']:
        return 'down'
    elif row['market_open_09:30'] < row['market_reg_close_16:00']:
        return 'up'
    else:
        return 'equal'

clean['day_direction_reg_16:00']= clean.apply(determine_direction, axis=1)
clean.head()

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,...,day_of_week,market_open_09:30,initial_direction,above,below,contract_location,market_close_16:15,market_reg_close_16:00,day_direction_16:15,day_direction_reg_16:00
0,2022-12-12,3980.00,3980.50,3976.00,3977.50,8373.0,3977.900,2593,09:31:00,09:31:00,...,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75,up,up
1,2022-12-12,3977.25,3979.25,3975.25,3978.50,5649.0,3977.150,1895,09:32:00,09:32:00,...,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75,up,up
2,2022-12-12,3978.50,3979.75,3975.50,3978.75,5903.0,3978.200,2027,09:33:00,09:33:00,...,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75,up,up
3,2022-12-12,3978.50,3979.00,3973.75,3974.50,5902.0,3975.675,1996,09:34:00,09:34:00,...,Monday,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75,up,up
4,2022-12-12,3974.75,3978.25,3974.25,3976.50,6085.0,3976.350,2002,09:35:00,09:35:00,...,Monday,3976.25,below,3980.0,3968.0,3980.0,4020.25,4025.75,up,up

## 4.

In [26]:
def determine_direction(row):
    if row['initial_direction']== 'above' and row['day_direction_16:15']== 'down':
        return 'correct'
    elif row['initial_direction']== 'below' and row['day_direction_16:15']== 'up':
        return 'correct'
    else:
        return 'incorrect'

clean['philo_result']= clean.apply(determine_direction, axis=1)
clean.head()

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,...,market_open_09:30,initial_direction,above,below,contract_location,market_close_16:15,market_reg_close_16:00,day_direction_16:15,day_direction_reg_16:00,philo_result
0,2022-12-12,3980.00,3980.50,3976.00,3977.50,8373.0,3977.900,2593,09:31:00,09:31:00,...,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75,up,up,incorrect
1,2022-12-12,3977.25,3979.25,3975.25,3978.50,5649.0,3977.150,1895,09:32:00,09:32:00,...,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75,up,up,incorrect
2,2022-12-12,3978.50,3979.75,3975.50,3978.75,5903.0,3978.200,2027,09:33:00,09:33:00,...,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75,up,up,incorrect
3,2022-12-12,3978.50,3979.00,3973.75,3974.50,5902.0,3975.675,1996,09:34:00,09:34:00,...,3976.25,above,3980.0,3968.0,3968.0,4020.25,4025.75,up,up,incorrect
4,2022-12-12,3974.75,3978.25,3974.25,3976.50,6085.0,3976.350,2002,09:35:00,09:35:00,...,3976.25,below,3980.0,3968.0,3980.0,4020.25,4025.75,up,up,correct

## 5.

In [29]:
def determine_direction(row):
    if row['initial_direction']== 'above' and row['market_close_16:15'] < row['contract_location']:
        return 'yes'
    elif row['initial_direction']== 'below' and row['market_close_16:15'] > row['contract_location']:
        return 'yes'
    else:
        return 'no'

clean['money_made']=clean.apply(determine_direction, axis=1)
clean.head()

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,...,initial_direction,above,below,contract_location,market_close_16:15,market_reg_close_16:00,day_direction_16:15,day_direction_reg_16:00,philo_result,money_made
0,2022-12-12,3980.00,3980.50,3976.00,3977.50,8373.0,3977.900,2593,09:31:00,09:31:00,...,above,3980.0,3968.0,3968.0,4020.25,4025.75,up,up,incorrect,no
1,2022-12-12,3977.25,3979.25,3975.25,3978.50,5649.0,3977.150,1895,09:32:00,09:32:00,...,above,3980.0,3968.0,3968.0,4020.25,4025.75,up,up,incorrect,no
2,2022-12-12,3978.50,3979.75,3975.50,3978.75,5903.0,3978.200,2027,09:33:00,09:33:00,...,above,3980.0,3968.0,3968.0,4020.25,4025.75,up,up,incorrect,no
3,2022-12-12,3978.50,3979.00,3973.75,3974.50,5902.0,3975.675,1996,09:34:00,09:34:00,...,above,3980.0,3968.0,3968.0,4020.25,4025.75,up,up,incorrect,no
4,2022-12-12,3974.75,3978.25,3974.25,3976.50,6085.0,3976.350,2002,09:35:00,09:35:00,...,below,3980.0,3968.0,3980.0,4020.25,4025.75,up,up,correct,yes

## 6.

In [32]:
def determine_direction(row):
    difference = abs(row['market_open_09:30'] - row['market_close_16:15'])  # Fix variable name
    return difference

clean['diff_open_close'] = clean.apply(determine_direction, axis=1)  # Ensure column exists
print(clean.head(75))

          date  candle_open_price  candle_high_price  candle_low_price  \
0   2022-12-12            3980.00            3980.50           3976.00
1   2022-12-12            3977.25            3979.25           3975.25
2   2022-12-12            3978.50            3979.75           3975.50
3   2022-12-12            3978.50            3979.00           3973.75
4   2022-12-12            3974.75            3978.25           3974.25
..         ...                ...                ...               ...
70  2022-12-13            4095.25            4095.50           4085.75
71  2022-12-13            4092.00            4093.00           4084.75
72  2022-12-13            4073.25            4080.25           4073.25
73  2022-12-13            4085.50            4089.50           4085.50
74  2022-12-13            4080.00            4083.25           4078.75

    candle_close_price   volume   average  bar_count      time confirm_time  \
0              3977.50   8373.0  3977.900       2593  09:31:00     09:31:00
1              3978.50   5649.0  3977.150       1895  09:32:00     09:32:00
2              3978.75   5903.0  3978.200       2027  09:33:00     09:33:00
3              3974.50   5902.0  3975.675       1996  09:34:00     09:34:00
4              3976.50   6085.0  3976.350       2002  09:35:00     09:35:00
..                 ...      ...       ...        ...       ...          ...
70             4090.50  10528.0  4089.225       3450  10:25:00     10:25:00
71             4087.50   7235.0  4088.075       2353  10:30:00     10:30:00
72             4079.50   8527.0  4077.100       3172  10:40:00     10:40:00
73             4088.75   4953.0  4087.800       1988  10:45:00     10:45:00
74             4081.00   4019.0  4081.025       1402  10:59:00     10:59:00

    ...   above   below  contract_location market_close_16:15  \
0   ...  3980.0  3968.0             3968.0            4020.25
1   ...  3980.0  3968.0             3968.0            4020.25
2   ...  3980.0  3968.0             3968.0            4020.25
3   ...  3980.0  3968.0             3968.0            4020.25
4   ...  3980.0  3968.0             3980.0            4020.25
..  ...     ...     ...                ...                ...
70  ...  4152.0  4140.0             4152.0            4055.50
71  ...  4152.0  4140.0             4152.0            4055.50
72  ...  4152.0  4140.0             4152.0            4055.50
73  ...  4152.0  4140.0             4152.0            4055.50
74  ...  4152.0  4140.0             4152.0            4055.50

    market_reg_close_16:00 day_direction_16:15  day_direction_reg_16:00  \
0                  4025.75                  up                       up
1                  4025.75                  up                       up
2                  4025.75                  up                       up
3                  4025.75                  up                       up
4                  4025.75                  up                       up
..                     ...                 ...                      ...
70                 4056.00                down                     down
71                 4056.00                down                     down
72                 4056.00                down                     down
73                 4056.00                down                     down
74                 4056.00                down                     down

    philo_result  money_made  diff_open_close
0      incorrect          no             44.0
1      incorrect          no             44.0
2      incorrect          no             44.0
3      incorrect          no             44.0
4        correct         yes             44.0
..           ...         ...              ...
70     incorrect          no             84.5
71     incorrect          no             84.5
72     incorrect          no             84.5
73     incorrect          no             84.5
74     incorrect          no             84.5

[75 rows x 26 columns]

## 7.

In [35]:
import numpy as np

clean['rounded_diff_open_close']= np.ceil(clean['diff_open_close'])

clean.head(75)

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,...,below,contract_location,market_close_16:15,market_reg_close_16:00,day_direction_16:15,day_direction_reg_16:00,philo_result,money_made,diff_open_close,rounded_diff_open_close
0,2022-12-12,3980.00,3980.50,3976.00,3977.50,8373.0,3977.900,2593,09:31:00,09:31:00,...,3968.0,3968.0,4020.25,4025.75,up,up,incorrect,no,44.0,44.0
1,2022-12-12,3977.25,3979.25,3975.25,3978.50,5649.0,3977.150,1895,09:32:00,09:32:00,...,3968.0,3968.0,4020.25,4025.75,up,up,incorrect,no,44.0,44.0
2,2022-12-12,3978.50,3979.75,3975.50,3978.75,5903.0,3978.200,2027,09:33:00,09:33:00,...,3968.0,3968.0,4020.25,4025.75,up,up,incorrect,no,44.0,44.0
3,2022-12-12,3978.50,3979.00,3973.75,3974.50,5902.0,3975.675,1996,09:34:00,09:34:00,...,3968.0,3968.0,4020.25,4025.75,up,up,incorrect,no,44.0,44.0
4,2022-12-12,3974.75,3978.25,3974.25,3976.50,6085.0,3976.350,2002,09:35:00,09:35:00,...,3968.0,3980.0,4020.25,4025.75,up,up,correct,yes,44.0,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2022-12-13,4095.25,4095.50,4085.75,4090.50,10528.0,4089.225,3450,10:25:00,10:25:00,...,4140.0,4152.0,4055.50,4056.00,down,down,incorrect,no,84.5,85.0
71,2022-12-13,4092.00,4093.00,4084.75,4087.50,7235.0,4088.075,2353,10:30:00,10:30:00,...,4140.0,4152.0,4055.50,4056.00,down,down,incorrect,no,84.5,85.0
72,2022-12-13,4073.25,4080.25,4073.25,4079.50,8527.0,4077.100,3172,10:40:00,10:40:00,...,4140.0,4152.0,4055.50,4056.00,down,down,incorrect,no,84.5,85.0
73,2022-12-13,4085.50,4089.50,4085.50,4088.75,4953.0,4087.800,1988,10:45:00,10:45:00,...,4140.0,4152.0,4055.50,4056.00,down,down,incorrect,no,84.5,85.0
74,2022-12-13,4080.00,4083.25,4078.75,4081.00,4019.0,4081.025,1402,10:59:00,10:59:00,...,4140.0,4152.0,4055.50,4056.00,down,down,incorrect,no,84.5,85.0

## 8.

In [38]:
import pandas as pd

def categorize_open_close_diff(df, column_name="rounded_diff_open_close"):
    """
    Categorizes the open-close difference into standard deviation intervals.

    Args:
    - df (DataFrame): The dataset containing open-close difference data.
    - column_name (str): The name of the column containing open-close difference values.

    Returns:
    - DataFrame with an added column categorizing the open-close difference.
    """
    # Compute mean and standard deviation of the specified column
    mean_val = df[column_name].mean()
    std_dev = df[column_name].std()

    # Define bins for standard deviation intervals
    bins = [-float("inf"), mean_val - 2*std_dev, mean_val - std_dev, mean_val, 
            mean_val + std_dev, mean_val + 2*std_dev, float("inf")]
    labels = ["Extremely Low", "Low", "Slightly Low", "Slightly High", "High", "Extremely High"]

    # Categorize each value into the appropriate standard deviation bin
    df["open_close_diff_sdv_interval"] = pd.cut(df[column_name], bins=bins, labels=labels)

    # Assign values to the nearest SD multiple
    df["open_close_diff_nearest_sdv"] = ((df[column_name] - mean_val) / std_dev).round()

    return df

# Example usage (assuming df is your actual dataset)
clean = categorize_open_close_diff(clean, column_name="rounded_diff_open_close")
clean.head(75)

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,...,market_close_16:15,market_reg_close_16:00,day_direction_16:15,day_direction_reg_16:00,philo_result,money_made,diff_open_close,rounded_diff_open_close,open_close_diff_sdv_interval,open_close_diff_nearest_sdv
0,2022-12-12,3980.00,3980.50,3976.00,3977.50,8373.0,3977.900,2593,09:31:00,09:31:00,...,4020.25,4025.75,up,up,incorrect,no,44.0,44.0,Slightly High,1.0
1,2022-12-12,3977.25,3979.25,3975.25,3978.50,5649.0,3977.150,1895,09:32:00,09:32:00,...,4020.25,4025.75,up,up,incorrect,no,44.0,44.0,Slightly High,1.0
2,2022-12-12,3978.50,3979.75,3975.50,3978.75,5903.0,3978.200,2027,09:33:00,09:33:00,...,4020.25,4025.75,up,up,incorrect,no,44.0,44.0,Slightly High,1.0
3,2022-12-12,3978.50,3979.00,3973.75,3974.50,5902.0,3975.675,1996,09:34:00,09:34:00,...,4020.25,4025.75,up,up,incorrect,no,44.0,44.0,Slightly High,1.0
4,2022-12-12,3974.75,3978.25,3974.25,3976.50,6085.0,3976.350,2002,09:35:00,09:35:00,...,4020.25,4025.75,up,up,correct,yes,44.0,44.0,Slightly High,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2022-12-13,4095.25,4095.50,4085.75,4090.50,10528.0,4089.225,3450,10:25:00,10:25:00,...,4055.50,4056.00,down,down,incorrect,no,84.5,85.0,Extremely High,3.0
71,2022-12-13,4092.00,4093.00,4084.75,4087.50,7235.0,4088.075,2353,10:30:00,10:30:00,...,4055.50,4056.00,down,down,incorrect,no,84.5,85.0,Extremely High,3.0
72,2022-12-13,4073.25,4080.25,4073.25,4079.50,8527.0,4077.100,3172,10:40:00,10:40:00,...,4055.50,4056.00,down,down,incorrect,no,84.5,85.0,Extremely High,3.0
73,2022-12-13,4085.50,4089.50,4085.50,4088.75,4953.0,4087.800,1988,10:45:00,10:45:00,...,4055.50,4056.00,down,down,incorrect,no,84.5,85.0,Extremely High,3.0
74,2022-12-13,4080.00,4083.25,4078.75,4081.00,4019.0,4081.025,1402,10:59:00,10:59:00,...,4055.50,4056.00,down,down,incorrect,no,84.5,85.0,Extremely High,3.0

## 9.

In [41]:
def determine_direction(row):
    difference = abs(row['market_open_09:30'] - row['contract_location'])  # Fix variable name
    return difference

clean['diff_open_conLoc']= clean.apply(determine_direction, axis=1)  # Ensure column exists
print(clean.head(75))

clean.to_csv('clean.csv', index=False)

          date  candle_open_price  candle_high_price  candle_low_price  \
0   2022-12-12            3980.00            3980.50           3976.00
1   2022-12-12            3977.25            3979.25           3975.25
2   2022-12-12            3978.50            3979.75           3975.50
3   2022-12-12            3978.50            3979.00           3973.75
4   2022-12-12            3974.75            3978.25           3974.25
..         ...                ...                ...               ...
70  2022-12-13            4095.25            4095.50           4085.75
71  2022-12-13            4092.00            4093.00           4084.75
72  2022-12-13            4073.25            4080.25           4073.25
73  2022-12-13            4085.50            4089.50           4085.50
74  2022-12-13            4080.00            4083.25           4078.75

    candle_close_price   volume   average  bar_count      time confirm_time  \
0              3977.50   8373.0  3977.900       2593  09:31:00     09:31:00
1              3978.50   5649.0  3977.150       1895  09:32:00     09:32:00
2              3978.75   5903.0  3978.200       2027  09:33:00     09:33:00
3              3974.50   5902.0  3975.675       1996  09:34:00     09:34:00
4              3976.50   6085.0  3976.350       2002  09:35:00     09:35:00
..                 ...      ...       ...        ...       ...          ...
70             4090.50  10528.0  4089.225       3450  10:25:00     10:25:00
71             4087.50   7235.0  4088.075       2353  10:30:00     10:30:00
72             4079.50   8527.0  4077.100       3172  10:40:00     10:40:00
73             4088.75   4953.0  4087.800       1988  10:45:00     10:45:00
74             4081.00   4019.0  4081.025       1402  10:59:00     10:59:00

    ...  market_reg_close_16:00  day_direction_16:15  day_direction_reg_16:00  \
0   ...                 4025.75                   up                       up
1   ...                 4025.75                   up                       up
2   ...                 4025.75                   up                       up
3   ...                 4025.75                   up                       up
4   ...                 4025.75                   up                       up
..  ...                     ...                  ...                      ...
70  ...                 4056.00                 down                     down
71  ...                 4056.00                 down                     down
72  ...                 4056.00                 down                     down
73  ...                 4056.00                 down                     down
74  ...                 4056.00                 down                     down

   philo_result  money_made diff_open_close  rounded_diff_open_close  \
0     incorrect          no            44.0                     44.0
1     incorrect          no            44.0                     44.0
2     incorrect          no            44.0                     44.0
3     incorrect          no            44.0                     44.0
4       correct         yes            44.0                     44.0
..          ...         ...             ...                      ...
70    incorrect          no            84.5                     85.0
71    incorrect          no            84.5                     85.0
72    incorrect          no            84.5                     85.0
73    incorrect          no            84.5                     85.0
74    incorrect          no            84.5                     85.0

    open_close_diff_sdv_interval  open_close_diff_nearest_sdv  \
0                  Slightly High                          1.0
1                  Slightly High                          1.0
2                  Slightly High                          1.0
3                  Slightly High                          1.0
4                  Slightly High                          1.0
..                           ...                          ...
70                Extremely High                          3.0
71                Extremely High                          3.0
72                Extremely High                          3.0
73                Extremely High                          3.0
74                Extremely High                          3.0

    diff_open_conLoc
0               8.25
1               8.25
2               8.25
3               8.25
4               3.75
..               ...
70             12.00
71             12.00
72             12.00
73             12.00
74             12.00

[75 rows x 30 columns]

## 10.

In [44]:
import pandas as pd

def categorize_open_conLoc_diff(df, column_name="'diff_open_conLoc"):
    """
    Categorizes the open-contract location difference into standard deviation intervals.

    Args:
    - df (DataFrame): The dataset containing open-close difference data.
    - column_name (str): The name of the column containing open-close difference values.

    Returns:
    - DataFrame with an added column categorizing the open-close difference.
    """
    # Compute mean and standard deviation of the specified column
    mean_val = df[column_name].mean()
    std_dev = df[column_name].std()

    # Define bins for standard deviation intervals
    bins = [-float("inf"), mean_val - 2*std_dev, mean_val - std_dev, mean_val, 
            mean_val + std_dev, mean_val + 2*std_dev, float("inf")]
    labels = ["Extremely Low", "Low", "Slightly Low", "Slightly High", "High", "Extremely High"]

    # Categorize each value into the appropriate standard deviation bin
    df["open_conLoc_diff_sdv_interval"] = pd.cut(df[column_name], bins=bins, labels=labels)

    # Assign values to the nearest SD multiple
    df["open_conLoc_diff_nearest_sdv"] = ((df[column_name] - mean_val) / std_dev).round()

    return df

# Example usage (assuming df is your actual dataset)
clean = categorize_open_conLoc_diff(clean, column_name="diff_open_conLoc")
clean.head(75)

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,...,day_direction_reg_16:00,philo_result,money_made,diff_open_close,rounded_diff_open_close,open_close_diff_sdv_interval,open_close_diff_nearest_sdv,diff_open_conLoc,open_conLoc_diff_sdv_interval,open_conLoc_diff_nearest_sdv
0,2022-12-12,3980.00,3980.50,3976.00,3977.50,8373.0,3977.900,2593,09:31:00,09:31:00,...,up,incorrect,no,44.0,44.0,Slightly High,1.0,8.25,Slightly High,1.0
1,2022-12-12,3977.25,3979.25,3975.25,3978.50,5649.0,3977.150,1895,09:32:00,09:32:00,...,up,incorrect,no,44.0,44.0,Slightly High,1.0,8.25,Slightly High,1.0
2,2022-12-12,3978.50,3979.75,3975.50,3978.75,5903.0,3978.200,2027,09:33:00,09:33:00,...,up,incorrect,no,44.0,44.0,Slightly High,1.0,8.25,Slightly High,1.0
3,2022-12-12,3978.50,3979.00,3973.75,3974.50,5902.0,3975.675,1996,09:34:00,09:34:00,...,up,incorrect,no,44.0,44.0,Slightly High,1.0,8.25,Slightly High,1.0
4,2022-12-12,3974.75,3978.25,3974.25,3976.50,6085.0,3976.350,2002,09:35:00,09:35:00,...,up,correct,yes,44.0,44.0,Slightly High,1.0,3.75,Slightly Low,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2022-12-13,4095.25,4095.50,4085.75,4090.50,10528.0,4089.225,3450,10:25:00,10:25:00,...,down,incorrect,no,84.5,85.0,Extremely High,3.0,12.00,High,2.0
71,2022-12-13,4092.00,4093.00,4084.75,4087.50,7235.0,4088.075,2353,10:30:00,10:30:00,...,down,incorrect,no,84.5,85.0,Extremely High,3.0,12.00,High,2.0
72,2022-12-13,4073.25,4080.25,4073.25,4079.50,8527.0,4077.100,3172,10:40:00,10:40:00,...,down,incorrect,no,84.5,85.0,Extremely High,3.0,12.00,High,2.0
73,2022-12-13,4085.50,4089.50,4085.50,4088.75,4953.0,4087.800,1988,10:45:00,10:45:00,...,down,incorrect,no,84.5,85.0,Extremely High,3.0,12.00,High,2.0
74,2022-12-13,4080.00,4083.25,4078.75,4081.00,4019.0,4081.025,1402,10:59:00,10:59:00,...,down,incorrect,no,84.5,85.0,Extremely High,3.0,12.00,High,2.0

## 11.

In [51]:
def calculate_streaks(df):
    # Sort to maintain temporal order
    df = df.sort_values(by=["date", "time"]).reset_index(drop=True)

    # Add empty columns
    df["dow_win_streak"] = 0
    df["dow_loss_streak"] = 0

    # Group by day of week and time
    grouped = df.groupby(["day_of_week", "time"])

    # Loop through each group
    for (day, time), group in grouped:
        win_streak = 0
        loss_streak = 0
        for idx in group.index:
            if df.loc[idx, "money_made"] == "yes":
                win_streak += 1
                loss_streak = 0
            elif df.loc[idx, "money_made"] == "no":
                loss_streak += 1
                win_streak = 0
            else:
                win_streak = 0
                loss_streak = 0

            # Write back to the original dataframe
            df.loc[idx, "dow_win_streak"] = win_streak
            df.loc[idx, "dow_loss_streak"] = loss_streak

    return df

clean= calculate_streaks(clean)

In [53]:
clean.head()

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,...,money_made,diff_open_close,rounded_diff_open_close,open_close_diff_sdv_interval,open_close_diff_nearest_sdv,diff_open_conLoc,open_conLoc_diff_sdv_interval,open_conLoc_diff_nearest_sdv,dow_win_streak,dow_loss_streak
0,2022-12-12,3980.00,3980.50,3976.00,3977.50,8373.0,3977.900,2593,09:31:00,09:31:00,...,no,44.0,44.0,Slightly High,1.0,8.25,Slightly High,1.0,0,1
1,2022-12-12,3977.25,3979.25,3975.25,3978.50,5649.0,3977.150,1895,09:32:00,09:32:00,...,no,44.0,44.0,Slightly High,1.0,8.25,Slightly High,1.0,0,1
2,2022-12-12,3978.50,3979.75,3975.50,3978.75,5903.0,3978.200,2027,09:33:00,09:33:00,...,no,44.0,44.0,Slightly High,1.0,8.25,Slightly High,1.0,0,1
3,2022-12-12,3978.50,3979.00,3973.75,3974.50,5902.0,3975.675,1996,09:34:00,09:34:00,...,no,44.0,44.0,Slightly High,1.0,8.25,Slightly High,1.0,0,1
4,2022-12-12,3974.75,3978.25,3974.25,3976.50,6085.0,3976.350,2002,09:35:00,09:35:00,...,yes,44.0,44.0,Slightly High,1.0,3.75,Slightly Low,-1.0,1,0

## 12.

In [55]:
def calculate_streaks_by_time(df):
    df = df.sort_values(by=["date", "time"]).reset_index(drop=True)
    df["overall_win_streak"] = 0
    df["overall_loss_streak"] = 0

    # Group only by time (ignore day_of_week)
    grouped = df.groupby("time")

    for time, group in grouped:
        win_streak = 0
        loss_streak = 0
        for idx in group.index:
            if df.loc[idx, "money_made"] == "yes":
                win_streak += 1
                loss_streak = 0
            elif df.loc[idx, "money_made"] == "no":
                loss_streak += 1
                win_streak = 0
            else:
                win_streak = 0
                loss_streak = 0

            df.loc[idx, "overall_win_streak"] = win_streak
            df.loc[idx, "overall_loss_streak"] = loss_streak

    return df

clean= calculate_streaks_by_time(clean)
clean.head()

,date,candle_open_price,candle_high_price,candle_low_price,candle_close_price,volume,average,bar_count,time,confirm_time,...,rounded_diff_open_close,open_close_diff_sdv_interval,open_close_diff_nearest_sdv,diff_open_conLoc,open_conLoc_diff_sdv_interval,open_conLoc_diff_nearest_sdv,dow_win_streak,dow_loss_streak,overall_win_streak,overall_loss_streak
0,2022-12-12,3980.00,3980.50,3976.00,3977.50,8373.0,3977.900,2593,09:31:00,09:31:00,...,44.0,Slightly High,1.0,8.25,Slightly High,1.0,0,1,0,1
1,2022-12-12,3977.25,3979.25,3975.25,3978.50,5649.0,3977.150,1895,09:32:00,09:32:00,...,44.0,Slightly High,1.0,8.25,Slightly High,1.0,0,1,0,1
2,2022-12-12,3978.50,3979.75,3975.50,3978.75,5903.0,3978.200,2027,09:33:00,09:33:00,...,44.0,Slightly High,1.0,8.25,Slightly High,1.0,0,1,0,1
3,2022-12-12,3978.50,3979.00,3973.75,3974.50,5902.0,3975.675,1996,09:34:00,09:34:00,...,44.0,Slightly High,1.0,8.25,Slightly High,1.0,0,1,0,1
4,2022-12-12,3974.75,3978.25,3974.25,3976.50,6085.0,3976.350,2002,09:35:00,09:35:00,...,44.0,Slightly High,1.0,3.75,Slightly Low,-1.0,1,0,1,0

In [57]:
clean.to_csv('clean.csv', index=False)